[build]
  base = "."
  publish = "dist"
  command = "npm ci && npm run build"
  functions = "functions"

# Redirection des routes API vers les fonctions Netlify
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Toutes les autres routes sont gérées par l'application React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
